apiVersion: v1
kind: ConfigMap
metadata:
  name: appprueba2-config
  namespace: bup-policies-pro
  labels:
    app.kubernetes.io/name: appprueba2
    app.kubernetes.io/part-of: bup-policies-pro
    app.kubernetes.io/managed-by: argocd
data:
  # Configuración de la aplicación appprueba2.
  # Agregar variables de entorno aquí.
  APP_NAME: "appprueba2"
  APP_ENV: "dev"
  APP_PORT: "8080"
