apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.appName }}
  namespace: ${{ values.projectName }}
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/part-of: ${{ values.projectName }}
    app.kubernetes.io/managed-by: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ${{ values.appName }}.${{ values.projectName }}.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.appName }}
                port:
                  name: http
