# kustomization.yaml — backstage overlay dev
# Referencia el base/ sin parches adicionales para el entorno local.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
