# namespace.yaml — test-proyecto
# Namespace del proyecto. Creado y gestionado via GitOps por ArgoCD.

apiVersion: v1
kind: Namespace
metadata:
  name: test-proyecto
  labels:
    app.kubernetes.io/managed-by: argocd
    idp/project: test-proyecto
