apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emulador-nintendo-emulador
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: emulador-nintendo
spec:
  project: default

  source:
    repoURL: https://github.com/NicoMiretti/idp-local.git
    targetRevision: HEAD
    path: gitops/platform/emulador-nintendo/base/apps/emulador

  destination:
    server: https://kubernetes.default.svc
    namespace: emulador-nintendo

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
