apiVersion: v1
kind: Secret
metadata:
  name: emulador-nintendo-secret
  namespace: emulador-nintendo
  labels:
    app.kubernetes.io/part-of: emulador-nintendo
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  PLACEHOLDER: "replace-me"
