apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-primera-app-config
  namespace: test-proyecto
  labels:
    app.kubernetes.io/name: mi-primera-app
    app.kubernetes.io/part-of: test-proyecto
    app.kubernetes.io/managed-by: argocd
data:
  # Configuración de la aplicación mi-primera-app.
  # Agregar variables de entorno aquí.
  APP_NAME: "mi-primera-app"
  APP_ENV: "dev"
  APP_PORT: "8080"
