apiVersion: v1
kind: Service
metadata:
  name: mi-primera-app
  namespace: test-proyecto
  labels:
    app.kubernetes.io/name: mi-primera-app
    app.kubernetes.io/part-of: test-proyecto
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mi-primera-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
